name: Example of cURL action

on: [ push ]
jobs:
    test-curl-action:
        name: 'Perform REST API'
        runs-on: ubuntu-latest
        steps:
            - name: 'Call API'
              uses: indiesdev/curl@v1
              id: api
              with:
                url: https://api.testproject.io/v2/projects/m_wv41nxx0qHyIreGqFzcA/jobs/Q141ZxB4MECl4zaSoyJrYQ/run
                method: 'POST'
                accept: 201,200
                headers: '{ "accept": "application/json", "Authorization": "NjJStEVYofrtP1NgTUT3ya6Fuq4SjlsJlqZTATc-EuY1","Content-Type": "application/json"}'
                body: '{ "agentId": "y_qVvwWKH0ixXvMO1B4GdQ" }'
                timeout: 10000
                
            - name: 'Use response'
              run: echo ${{ steps.api.outputs.response }}
