on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://api.testproject.io/v2/projects/m_wv41nxx0qHyIreGqFzcA/jobs/GdeSZtQwpUKxW0c8_nIiBw/run
