on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -X POST "https://api.testproject.io/v2/projects/m_wv41nxx0qHyIreGqFzcA/jobs/GdeSZtQwpUKxW0c8_nIiBw/run" -H "accept: application/json" -H "Authorization: NjJStEVYofrtP1NgTUT3ya6Fuq4SjlsJlqZTATc-EuY1" -H "Content-Type: application/json" -d "{ \"agentId\": \"4MNyrrCGlU--SN9s-8H8xg\",}"
